# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gate.service.grpc.api import service_pb2 as gate_dot_service_dot_grpc_dot_api_dot_service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class RootStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Init = channel.unary_unary(
        '/gate.service.grpc.api.Root/Init',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.InitRequest.SerializeToString,
        response_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.InitResponse.FromString,
        )


class RootServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RootServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Init': grpc.unary_unary_rpc_method_handler(
          servicer.Init,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.InitRequest.FromString,
          response_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.InitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gate.service.grpc.api.Root', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class InstanceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/gate.service.grpc.api.Instance/Create',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.CreateRequest.SerializeToString,
        response_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.CreateResponse.FromString,
        )
    self.Receive = channel.unary_stream(
        '/gate.service.grpc.api.Instance/Receive',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.ReceiveRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.FromString,
        )
    self.Handle = channel.unary_unary(
        '/gate.service.grpc.api.Instance/Handle',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.HandleRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Shutdown = channel.unary_unary(
        '/gate.service.grpc.api.Instance/Shutdown',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.ShutdownRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Suspend = channel.unary_unary(
        '/gate.service.grpc.api.Instance/Suspend',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.SuspendRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Snapshot = channel.unary_unary(
        '/gate.service.grpc.api.Instance/Snapshot',
        request_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.SnapshotRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.FromString,
        )


class InstanceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Receive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Handle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Shutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Suspend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Snapshot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstanceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.CreateRequest.FromString,
          response_serializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.CreateResponse.SerializeToString,
      ),
      'Receive': grpc.unary_stream_rpc_method_handler(
          servicer.Receive,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.ReceiveRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.SerializeToString,
      ),
      'Handle': grpc.unary_unary_rpc_method_handler(
          servicer.Handle,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.HandleRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.Shutdown,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.ShutdownRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Suspend': grpc.unary_unary_rpc_method_handler(
          servicer.Suspend,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.SuspendRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Snapshot': grpc.unary_unary_rpc_method_handler(
          servicer.Snapshot,
          request_deserializer=gate_dot_service_dot_grpc_dot_api_dot_service__pb2.SnapshotRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BytesValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gate.service.grpc.api.Instance', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
